/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathgame;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.midi.Sequencer;
import javax.swing.JLabel;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.Timer;

/**
 *
 * @author Levit Nudi
 */
public class GameUI extends javax.swing.JFrame {

    
//DO NOT RENAME BELOW VARIABLES    
int count_timer = 60;
int max_time = 60;//one minute
int user_score = 0;
int first_number = 0;
int second_number = 0;
int user_guess = 0;
int correct_answer = 0;
int max_number_of_questions = 10;
int number_of_answered_questions = 0;
String beep = "beep.wav";
String music = "music.mid";//feel free to change the music and sound effects
//music will start playing inside formWindowOpened() method. This is called
//when the game window is opened
String score = "score.wav";
//DO NOT RENAME ABOVE VARIABLES 
    /**
     * Creates new form GameUI
     * 
     * 
     * WARNING
     * 
     * ANY FORM OF DISHONESTY OR PLAGIARISM WILL LEAD TO DISQUALIFICATION
     * 
     * 
     * FUNDAMENTALS OF COMPUTER SCIENCE SEM1 (30 points)
     * Instructions
     * 
     * 
     * PART A (10 points)
     * 1. Let Quit menu button close the application
     * 2. disable guess button when time is up (use setEnabled(false) method on the button) and enable it
     * when game start button is clicked
     * 3. Rename ALL variable names of swing components, e.g labels, button, textFields etc
     * 
     * 
     * PART B (10 points)
     * 1. Create Another GUI using JDialog called HelpDialog similar to AboutDialog
     * 2. Give the dialog a title of 'Help' and use specifications for AboutDialog(font size etc)
     * 3. Use labels to describe how the game is played
     * 4. Use serif font for your descriptions
     * 5. Add a close button similar to the one in AboutDialog and make the click action close the dialog
     * 6. When the user clicks Tutorial under help menu, let it open HelpDialog (see how AboutDialog opens)
     * 
     * 
     * PART C (10 points)
     * 1. Package application using launch4j
     * 2. Add splash screen and use YOUR OWN icon and image
     * you can get free icons from (http://www.iconarchive.com/tag/ico-files)
     * and any image from google for your splash screen
     * 
     * 
     * ENGINEERING TOOLKIT (30 points)
     * Push your project to github (15 points)
     * detail your github project (15 points)
     * submit your github link by Friday 17th (August) 2018
     * late submissions will not be accepted
     * 
     * 
     * 
     */
    public GameUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        Mylabel01 = new javax.swing.JLabel();
        Label02 = new javax.swing.JLabel();
        Label03 = new javax.swing.JLabel();
        Mylabel05 = new javax.swing.JLabel();
        Mylabel5 = new javax.swing.JLabel();
        MyLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Button01 = new javax.swing.JButton();
        Mymenubar1 = new javax.swing.JMenuBar();
        MENU01 = new javax.swing.JMenu();
        Menu1 = new javax.swing.JMenuItem();
        Menu3 = new javax.swing.JMenuItem();
        Mymenu2 = new javax.swing.JMenu();
        Mymenu4 = new javax.swing.JMenuItem();
        Mymenu5 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Mylabel01.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Mylabel01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mylabel01.setText("MATH GAME");

        Label02.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Label02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label02.setText("0");

        Label03.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Label03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label03.setText("Question");

        Mylabel05.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mylabel05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mylabel05.setText("Timer :");

        Mylabel5.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Mylabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mylabel5.setText("60");

        MyLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MyLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MyLabel6.setText("Score :");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Button01.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button01.setText("Guess");
        Button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button01ActionPerformed(evt);
            }
        });

        MENU01.setText("Menu");

        Menu1.setText("Start Game");
        Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ActionPerformed(evt);
            }
        });
        MENU01.add(Menu1);

        Menu3.setText("Quit");
        MENU01.add(Menu3);

        Mymenubar1.add(MENU01);

        Mymenu2.setText("Help");
        Mymenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mymenu2ActionPerformed(evt);
            }
        });

        Mymenu4.setText("About");
        Mymenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mymenu4ActionPerformed(evt);
            }
        });
        Mymenu2.add(Mymenu4);

        Mymenu5.setText("Tutorial");
        Mymenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mymenu5ActionPerformed(evt);
            }
        });
        Mymenu2.add(Mymenu5);

        Mymenubar1.add(Mymenu2);

        setJMenuBar(Mymenubar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mylabel05, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mylabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(82, 82, 82)
                .addComponent(Label02, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(Button01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(Mylabel01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(Mylabel01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mylabel05)
                    .addComponent(MyLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mylabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label03, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button01, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ActionPerformed
        // TODO add your handling code here:
        //check the timer class in the code, set repeat and start
        //if timer was running stop it else start        
        count_timer = 0;
        if(!timer.isRunning()){
        timer.setRepeats(true);
        timer.start();
        }else{
            //then restart
            timer.stop();
            timer.setRepeats(true);
            timer.start();
        }
        number_of_answered_questions = 0;//reset number of questions answered to 0 if at all above 0
        generateQuestion();
    }//GEN-LAST:event_Menu1ActionPerformed

    private void Button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button01ActionPerformed
        // TODO add your handling code here: 
        
        Button01.setEnabled(true);
        playSound(beep);
        if(!hasNoInput()){
        //check if user input matches with correct answer
        user_guess = Integer.parseInt(String.valueOf(jTextField1.getText()));
        if(user_guess == correct_answer){
            
          //increment and display score
            user_score++;
            Label02.setText(String.valueOf(user_score));
            playSound(score);
            
            //clear previous input
            jTextField1.setText(null);
            
            //generate next question
            generateQuestion();
           showPopup("Correct!");
        }else{
            //clear previous input
            jTextField1.setText(null);
            //move to the next question even when user gets wrong
             generateQuestion();
            showPopup("The correct answer is "+correct_answer);
        }
        }else{
            showPopup("Answer cannot be empty!");
        }
        
        
    }//GEN-LAST:event_Button01ActionPerformed

    private void Mymenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mymenu4ActionPerformed
        // TODO add your handling code here:
      playSound(beep);  
      AboutDialog aboutDialog = new AboutDialog(this, true);
      aboutDialog.show();
    }//GEN-LAST:event_Mymenu4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
           
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         playSound(music); 
    }//GEN-LAST:event_formWindowOpened

    private void Mymenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mymenu5ActionPerformed
        // TODO add your handling code here:
   HelpDialogue helpDialogue = new HelpDialogue(this, true);
       helpDialogue.show();
        
    }//GEN-LAST:event_Mymenu5ActionPerformed

    private void Mymenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mymenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mymenu2ActionPerformed

    //this method will generate a question with two random numbers
    //and display on the question label
    private void generateQuestion(){
      //randomly pick any number between 0 and 4 
      //based on the number picked, the question will
      //either be addition, subtraction, multiplication or division   
        
        
      
        //limit number of questions answered
      if(number_of_answered_questions < max_number_of_questions){  
        
      Random operation = new Random(); 
      
      //pick any random number between 0 and 20      
      first_number = new Random().nextInt(20);
       //pick any random number between 0 and 10 
      second_number = new Random().nextInt(10);      
          
  
      if(operation.nextInt(4)==0){
           Label03.setText(first_number+" + "+second_number);
             correct_answer = first_number+second_number; 
              System.out.println("Addition");
             
      }else if(operation.nextInt(4)==1){
           //if operation is 1 let's subtract
             
             Label03.setText(first_number+" - "+second_number);
             correct_answer = first_number-second_number;
                   System.out.println("Subtraction");             
      }else if(operation.nextInt(4)==2){
           //if operation is 2 let's multiply    
            
             Label03.setText(first_number+" x "+second_number);         
             correct_answer = first_number*second_number; 
                       System.out.println("Multiplication");             
      }else if(operation.nextInt(4)==3){
           //if operation is 3 let's divide      
             Label03.setText(first_number+" / "+second_number); 
             if(second_number!=0)
             correct_answer = first_number/second_number; 
             //if you divide a number by zero it throws arithmetic exception
             else correct_answer = first_number;
                           System.out.println("Division");
        
      }else if(operation.nextInt(4)==4){
               //if operation is 4 let's find the remainder when you divide
             Label03.setText("Remainder of "+first_number+" / "+second_number);                    
             correct_answer = first_number%second_number; 
                                 System.out.println("Remainder");
      }
      
      number_of_answered_questions++;
      
      }else {
          //stop timer if it was still running
        if(timer.isRunning()){  
        timer.stop();
        }
        Label03.setText("You Scored "+user_score+"!");
        Mylabel5.setText("Time Taken "+count_timer);
      }
      
    }
    
    //this method checks whether there's any input 
    public boolean hasNoInput(){        
    return jTextField1.getText().isEmpty();
    }
    
    
    public void showPopup(String message){
        final Popup p = PopupFactory.getSharedInstance()
                .getPopup(jTextField1, new JLabel(message), jTextField1.getX(), jTextField1.getY());
    p.show();
    // create a timer to hide the popup later
    Timer t = new Timer(5000, (ActionEvent e) -> {
        p.hide();
        });
    t.setRepeats(false);
    t.start();
    }
    
        Timer timer = new Timer(1000, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
          if(count_timer<max_time){    
          Mylabel5.setText("Time : "+max_time);
         max_time--;
         
          }else{
         Mylabel5.setText("Time Up!"); 
        
        }
        }
    });  
        
        
        
         // play beep or score sounds sound
   public void playSound(String soundName) {        
       //locate the sounds under resource folder
        URL url = GameUI.class.getResource(soundName);
       if(!soundName.equals(music)){  
          // play only once if not music
       AudioClip clip = Applet.newAudioClip(url);       
       clip.play();
       
       }else{
            try {
                //repeat forever until game is closed
                // ONLY WORKS WITH MIDI FILES !
                // Obtains the default Sequencer connected to a default device.
                URL url2 = GameUI.class.getResource(soundName);
                Sequencer sequencer = MidiSystem.getSequencer();
                //set loop to play until game is closed
                sequencer.setLoopCount(Sequencer.LOOP_CONTINUOUSLY);
                
                // Opens the device, indicating that it should now acquire any
                // system resources it requires and become operational.
                sequencer.open();
                
                // create a stream from a file
                InputStream is = new BufferedInputStream(new FileInputStream(new File(url2.getPath())));
                
                // Sets the current sequence on which the sequencer operates.   
                
                // The stream must point to MIDI file data.
                sequencer.setSequence(is);
                
                // Starts playback of the MIDI data in the currently loaded sequence.
                sequencer.start();
            } catch (MidiUnavailableException ex) {
                Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidMidiDataException ex) {
                Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
   }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameUI().setVisible(true);
        //Once the window is activated / application opens
        //let's play some background music
       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button01;
    private javax.swing.JLabel Label02;
    private javax.swing.JLabel Label03;
    private javax.swing.JMenu MENU01;
    private javax.swing.JMenuItem Menu1;
    private javax.swing.JMenuItem Menu3;
    private javax.swing.JLabel MyLabel6;
    private javax.swing.JLabel Mylabel01;
    private javax.swing.JLabel Mylabel05;
    private javax.swing.JLabel Mylabel5;
    private javax.swing.JMenu Mymenu2;
    private javax.swing.JMenuItem Mymenu4;
    private javax.swing.JMenuItem Mymenu5;
    private javax.swing.JMenuBar Mymenubar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
